// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzprmajPqgg92EqkOX2jukSZo9pGudpM',
    appId: '1:860775359798:web:695a84ae706e479179ff97',
    messagingSenderId: '860775359798',
    projectId: 'proyect-app-c12e6',
    authDomain: 'proyect-app-c12e6.firebaseapp.com',
    databaseURL: 'https://proyect-app-c12e6-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-app-c12e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBZowgNlY2QU5fqyarhMcRSwiRdsMLVU',
    appId: '1:860775359798:android:f0b0d3c889f22a7b79ff97',
    messagingSenderId: '860775359798',
    projectId: 'proyect-app-c12e6',
    databaseURL: 'https://proyect-app-c12e6-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-app-c12e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKjyuLKmb5mu1ZLTPdJ-SyXXWA8U1jRY',
    appId: '1:860775359798:ios:58c382bd82f21ee079ff97',
    messagingSenderId: '860775359798',
    projectId: 'proyect-app-c12e6',
    databaseURL: 'https://proyect-app-c12e6-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-app-c12e6.appspot.com',
    iosBundleId: 'com.example.tallerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKjyuLKmb5mu1ZLTPdJ-SyXXWA8U1jRY',
    appId: '1:860775359798:ios:58c382bd82f21ee079ff97',
    messagingSenderId: '860775359798',
    projectId: 'proyect-app-c12e6',
    databaseURL: 'https://proyect-app-c12e6-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-app-c12e6.appspot.com',
    iosBundleId: 'com.example.tallerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpzprmajPqgg92EqkOX2jukSZo9pGudpM',
    appId: '1:860775359798:web:987a151bfd0ecaee79ff97',
    messagingSenderId: '860775359798',
    projectId: 'proyect-app-c12e6',
    authDomain: 'proyect-app-c12e6.firebaseapp.com',
    databaseURL: 'https://proyect-app-c12e6-default-rtdb.firebaseio.com',
    storageBucket: 'proyect-app-c12e6.appspot.com',
  );
}
